version: '3'
services:
  bot:
    container_name: bot
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: 'on-failure'
    volumes:
      - ./api:/app/api
      - ./src:/app/src
    ports:
      - '5000:5000'
    # networks:
    #   - core-v4_sce-local
# networks:
#   core-v4_sce-local:
#     external: true
