version: '3'
services:
  bot:
    container_name: bot
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: 'on-failure'
    volumes:
      - ./api:/bot/api
      - ./src:/bot/src
      - ./server.js:/bot/server.js
      - ./config.json:/bot/config.json
