version: '3'
services:
  bot:
    container_name: bot
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: 'on-failure'
    volumes:
      - ./src:/bot/src
      - ./server.js:/bot/server.js
      